
  CREATE TABLE "DONATION_SECTION" 
   (	
    "DONATION_AMOUNT" NUMBER(10,0), 
	"TITLE" VARCHAR2(5 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"ADDRESS_1" VARCHAR2(50 BYTE), 
	"ADDRESS_2" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PROVINCE_STATE" VARCHAR2(2 BYTE), 
	"POSTAL_ZIP_CODE" VARCHAR2(7 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"CREDIT_CARD_NUMBER" VARCHAR2(16 BYTE), 
	"CARDHOLDERS_NAME" VARCHAR2(30 BYTE), 
	"EXPIRATION_DATE" VARCHAR2(5 BYTE), 
	"CARD_SECURITY_CODE" NUMBER(3,0), 
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) 
   
Insert into DONATION_SECTION (DONATION_AMOUNT,TITLE,FIRST_NAME,LAST_NAME,EMAIL,COUNTRY,ADDRESS_1,ADDRESS_2,CITY,PROVINCE_STATE,POSTAL_ZIP_CODE,PHONE,DESCRIPTION,CREDIT_CARD_NUMBER,CARDHOLDERS_NAME,EXPIRATION_DATE,CARD_SECURITY_CODE,ID) values (1000,'Mr.','Alan','Po','a.po@ukr.net','Ukraine','4 Zalupa str.','komnata 1','Kiev','KI','03039','0635779222','Grateful Patient or In Honour Donation','1423534635476743','Alan Po','10-20',231,45);
Insert into DONATION_SECTION (DONATION_AMOUNT,TITLE,FIRST_NAME,LAST_NAME,EMAIL,COUNTRY,ADDRESS_1,ADDRESS_2,CITY,PROVINCE_STATE,POSTAL_ZIP_CODE,PHONE,DESCRIPTION,CREDIT_CARD_NUMBER,CARDHOLDERS_NAME,EXPIRATION_DATE,CARD_SECURITY_CODE,ID) values (500,'Mr.','Alena','Pypkina','a.pyp@gmail.com','Canada','1 dundee dr','unit 5','Ottawa','ON','m3x 3w6','5198544499','In Memory Donation','2342342343223432','fsdsdfsd','10-19',324,44);
Insert into DONATION_SECTION (DONATION_AMOUNT,TITLE,FIRST_NAME,LAST_NAME,EMAIL,COUNTRY,ADDRESS_1,ADDRESS_2,CITY,PROVINCE_STATE,POSTAL_ZIP_CODE,PHONE,DESCRIPTION,CREDIT_CARD_NUMBER,CARDHOLDERS_NAME,EXPIRATION_DATE,CARD_SECURITY_CODE,ID) values (1000,'Mr.','Iurii','Iakymenko','7fold@ukr.net','Canada','8 Farmington place','Unit 716','Kitchener','ON','N2P 1Y3','4168228707','General Donation','2534665364564363','Iurii Iakymenko','08-18',324,3);


  ALTER TABLE "DONATION_SECTION" MODIFY ("CARDHOLDERS_NAME" NOT NULL ENABLE);
  ALTER TABLE "DONATION_SECTION" MODIFY ("EXPIRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "DONATION_SECTION" MODIFY ("CARD_SECURITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "DONATION_SECTION" MODIFY ("DONATION_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "DONATION_SECTION" MODIFY ("CREDIT_CARD_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "DONATION_SECTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DONATION_SECTION" ADD PRIMARY KEY ("ID")
  